### ISSUE TITLE
[NavigationBasicSample] crash

### ISSUE THREAD

**Issue by jaredtech** [googlesamples/android-architecture-components#446] opened 2018-08-17 09:23 UTC
TitleScreen ---> Register ---> Match ---> InGame ---> ResultsWinner/GameOver ---> Match,   then click 'Back Key' back to Register, then click SIGN UP,  crash.
log:
`com.example.android.navigationsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.navigationsample, PID: 3184
    java.lang.IllegalArgumentException: navigation destination com.example.android.navigationsample:id/action_register_to_match is unknown to this NavController
        at androidx.navigation.NavController.navigate(NavController.java:669)
        at androidx.navigation.NavController.navigate(NavController.java:628)
        at androidx.navigation.NavController.navigate(NavController.java:616)
        at com.example.android.navigationsample.Register$onCreateView$1.onClick(Register.kt:39)
        at android.view.View.performClick(View.java:6266)
        at android.view.View$PerformClick.run(View.java:24730)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6672)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)`

就是游戏一次无论输赢，回到匹配的界面，再点击返回按钮回到登录界面，再次点登录按钮会崩溃。
原因没有找到。

英文不好，大佬看到可以帮忙翻译一下，谢谢

**Comment by ChenPengHuang** [comment] 2018-09-11 02:46
https://github.com/googlesamples/android-architecture-components/issues/435

**Comment by gilgoldzweig** [comment] 2018-10-16 17:48
bug returns on 1.0.0-alpha06 ktx

```
java.lang.IllegalArgumentException: navigation destination com.nyx.tech.dev:id/action_home_fragment_to_calibration_fragment is unknown to this NavController
        at androidx.navigation.NavController.navigate(NavController.java:691)
        at androidx.navigation.NavController.navigate(NavController.java:648)
        at androidx.navigation.NavController.navigate(NavController.java:634)
        at androidx.navigation.NavController.navigate(NavController.java:712)
        at com.nyx.tech.fragments.home.HomeFragment.onFeatureInitiated(HomeFragment.kt:240)
        at com.nyx.tech.fragments.home.HomeFragmentPresenter$observe$1.onChanged(HomeFragmentPresenter.kt:177)
        at com.nyx.tech.fragments.home.HomeFragmentPresenter$observe$1.onChanged(HomeFragmentPresenter.kt:50)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at android.arch.lifecycle.LiveData$1.run(LiveData.java:87)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-14 15:23:52.527 23366-23427/com.nyx.tech.dev W/NYXApplication$onCreate: com
```

**Comment by tsuijten** [comment] 2018-11-02 18:31
I also ran into this issue...

**Comment by badoualy** [comment] 2018-11-13 14:45
I have a similar issue with alpha07 on my project, I'll try to reproduce on this sample.

**Comment by mikaelj** [comment] 2018-11-28 08:00
Me three.

**Comment by HGyllensvard** [comment] 2018-12-01 23:03
We also noticed these errors with alpha07 (Kotlin if it matters).

The root error in our case was if two navigations happened too close to one another.
Say we have Fragment A, B and C.
Somehow the application starts two navigations almost at the exact same time, like:
A navigates to B
A navigates to C

The navigation library will open fragment B, and then tries to perform the A -> C navigation, but looking at Fragment B's actions, which leads to a crash.

Once we realised this we could easily reproduce the error.

We noticed the problem in our recycler view with different items taking the user to different fragments.
One way would be to use an Atomic boolean which is reset in OnResume and then perform a getAndSet before trying to perform the navigation.

**Comment by Trumeet** [comment] 2018-12-02 20:03
+1 With Alpha 07

**Comment by mikaelj** [comment] 2018-12-06 20:59
Fixed in alpha08?

**Comment by keluokeda** [comment] 2018-12-12 02:34
+1 With Alpha 07

**Comment by itscorey** [comment] 2018-12-13 12:33
Same happening in version `alpha-08`.

The problem is occuring after clicking in two or more buttons (same time). 

Button A: navigate user to FragmentA
Button B: navigate user to FragmentB

When clicking in these buttons in the same time, crash occurs.

**Solution**: a workaround is to disable **both** buttons in **onClickListener**.

**Comment by kinnrot** [comment] 2019-01-09 19:04
I also encountered this issue, currently patching it with mutable live data, post value, which just pushes the navigation call to the end of the event loop, which is similar to Handler().post. seems to work fine for now.

**Comment by cedrtang** [comment] 2019-01-11 02:38
Had the same problem in `alpha-09`. I used a global action to pop back to `Root (self)` then doing any navigation on my graph would trigger the issue.

I solved it by setting my Activity `android:launchMode="singleTop"`in Manifest and instead of pop to `Root`, I pop to my Home Fragment directly.

**Comment by kinnrot** [comment] 2019-01-11 05:57
@cedrtang can you share before and after code ?

**Comment by cedrtang** [comment] 2019-01-11 21:10
@kinnrot Sure.

**Manifest.xml**
Before
`        <activity
            android:name=".ui.activities.MainActivity"
            android:label="@string/app_name"
            android:theme="@style/AppTheme.NoActionBar">`

After:
`        <activity
            android:name=".ui.activities.MainActivity"
            android:label="@string/app_name"
            android:theme="@style/AppTheme.NoActionBar"
            android:launchMode="singleTop">`

**nav_graph.xml**
Before:
`    <action
        android:id="@+id/action_nav_graph_pop"
        app:popUpTo="@id/nav_graph" />`

After:
`    <action
        android:id="@+id/action_nav_graph_pop"
        app:popUpTo="@id/homeFragment" />`

My navigation flow works all the way through a particular flow then back home and can do it again. Up and back navigation works as well. 

I use a mix of different methods to manage my navigation:
`Navigation.findNavController(getActivity(), R.id.nav_host_fragment).navigate(HomeFragmentDirections.actionHomeFragmentToLoginFragment(error, response.data));
`
`binding.finishBtn.setOnClickListener(v -> Navigation.findNavController(v).navigate(R.id.action_nav_graph_pop));`
`binding.anotherCardBtn.setOnClickListener(Navigation.createNavigateOnClickListener(R.id.action_nav_graph_pop));`

Hope it helps

**Comment by itscorey** [comment] 2019-01-25 12:53
Crash still happening in `alpha10` and `alpha-11`  even after a lot of bug fixes. :>

**Comment by Dwite** [comment] 2019-01-30 06:58
Any ideas how to fix it ?

**Comment by yosim199** [comment] 2019-02-05 12:03
Same here on alpha-11

**Comment by korydondzila** [comment] 2019-02-11 15:49
My nav actions will popup to the nav, with the destination as the home fragment. Here is an example, HistoryCalendarFragment can be reached from the WeeklyFragment. This action is used when clicking on a specific week in a calendar to go to that week in the WeeklyFragment. I'm not sure if maybe this the combined use of destination and popUpTo with Inclusive that solves the issue, but I do not get this crash.

`<action
    android:id="@+id/action_historyCalendarFragment_to_weeklyFragment"
    app:destination="@+id/weeklyFragment"
    app:popUpTo="@+id/nav_duty_hours"
    app:popUpToInclusive="true" />`

`findNavController().navigate(
    HistoryCalendarFragmentDirections.actionHistoryCalendarFragmentToWeeklyFragment(
        selectedWeek.toString()
    )
)`

Though I have had this crash when doing something like this:
`findNavController().popBackStack(R.id.nav_evaluations, false)`
In this instance the current fragment is two down from the root and want to get back to the root (i.e. like clicking home/back twice). This issue was fixed by instead doing this:
`findNavController().popBackStack(R.id.evaluationsFragment, false)`
Where instead of specifying the nav itself I specify the fragment.

As @cedrtang mentioned this seems to be an issue with popping to the root directly. I do not have SingleTop set in the Manifest.

**Comment by ianhanniballake** [comment] 2019-03-08 23:14
Please file issues with the Navigation library on the [issue tracker](https://issuetracker.google.com/issues/new?component=409828) with a sample project that reproduces your issue.

**Closed by ianhanniballake** 2019-03-08 23:14 UTC

**Comment by Keldmar** [comment] 2020-03-16 12:08
I wrote this extensions 
```
fun Fragment.navigateAction(action: NavDirections) {
    val navController = this.findNavController()
    if (navController.currentDestination?.getAction(action.actionId) == null) {
        return
    } else {
        navController.navigate(action)
    }
}
```

**Comment by BitMobix** [comment] 2020-09-20 17:30
I,m fixed bug.
Problem DONT UI thread...

This is working 
```
activity?.runOnUiThread{
                        findNavController().popBackStack()
                    }
```
