### ISSUE TITLE
Allow LiveData, Flowable for insert, update, delete

### ISSUE THREAD

**Issue by kg6zvp** [googlesamples/android-architecture-components#173] opened 2017-10-02 09:05 UTC
Having asynchronous insert, update and delete would reduce a lot of boilerplate code and really make this library feel more complete.

Are there any plans to at least look into adding this feature?

A use case: A user inputs data into a form and wants to be redirected to a "view form" type activity after the data is saved. I simply write `@Insert LiveData<Long> insert(Form form);` and observe, loading the other activity as soon as LiveData provides a response.

**Comment by mynote** [comment] 2017-10-02 10:10
Duplicate of  #162

**Comment by florina-muntenescu** [comment] 2017-10-04 13:28
There is already a bug raised for this on the official bug tracker, [here](https://issuetracker.google.com/63613835).

**Closed by florina-muntenescu** 2017-10-04 13:28 UTC
