### ISSUE TITLE
An exception occurred while scroll to load more

### ISSUE THREAD

**Issue by thosantaiba** [googlesamples/android-architecture-components#67] opened 2017-06-22 10:04 UTC
FATAL EXCEPTION: pool-1-thread-1
                                                 Process: com.android.example.github, PID: 6168
                                                 java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                     at com.android.example.github.repository.RepoRepository$3.saveCallResult(RepoRepository.java:135)
                                                     at com.android.example.github.repository.RepoRepository$3.saveCallResult(RepoRepository.java:132)
                                                     at com.android.example.github.repository.NetworkBoundResource.lambda$null$5$NetworkBoundResource(NetworkBoundResource.java:68)
                                                     at com.android.example.github.repository.NetworkBoundResource$$Lambda$3.run(Unknown Source)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by yigit** [comment] 2017-06-25 19:53
duplicate of #33

**Closed by yigit** 2017-06-25 19:53 UTC
